# This is a basic workflow to help you get started with Actions

name: Contribution Graph

# Controls when the workflow will run
on:
  schedule: 
    - cron: "0 0 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: JBraunsmaJr/contributiongraph@v1
        with:
           token: ${{ secrets.GRAPH_QL }}
           viewby: day
           farback: 31
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating Contribution Graph
          file_pattern: images/*
